# Generated by Django 4.1.7 on 2023-03-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('web_code', models.CharField(blank=True, max_length=128, null=True)),
                ('country_code', models.CharField(max_length=128, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number_length', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='countries/flags/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'db_table': 'general_country',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readonly', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('down', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'mode',
                'verbose_name_plural': 'mode',
                'db_table': 'mode',
                'ordering': ('id',),
            },
        ),
    ]
